
about :

  name : 'wTemplateTreeResolver'
  description : 'Class to resolve tree-like data structures with links  or paths in the structure. Use the module to resolve template or path to value.'
  version : '0.5.0'
  enabled : 1
  interpreters :
  - njs >= 8.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - Template tree
  - wTools
  - JSON
  - YAML
  license : MIT
  author : 'Kostiantyn Wandalen <wanalen@willbe.so>'
  contributors :
  - 'Kostiantyn Wandalen <wanalen@willbe.so>'
  npm.name : 'wtemplatetreeresolver'
  npm.scripts :
    test : 'wtest .run proto/**'
    docgen : 'wdocgen .build proto'

path :

  repository : git+https:///github.com/Wandalen/wTemplateTreeResolver.git
  bugtracker : https:///github.com/Wandalen/wTemplateTreeResolver/issues

step :

  proto.export :
    inherit : module.export
    export : path::proto
    tar : 0
    criterion :
      content : 'proto'

  doc.export :
    inherit : module.export
    export : path::doc
    tar : 0
    criterion :
      content : 'doc'

  npm.export :
    inherit : module.export
    export : out.npm
    tar : 0
    criterion :
      content : 'npm'

  npm.publish :
    shell : npm publish

build :

  proto.export :
    criterion :
      content : 'proto'
      export : 1
    steps :
      # - build::debug.raw
      - step::proto.export

  doc.export :
    criterion :
      content : 'doc'
      export : 1
    steps :
      # - build::debug.raw
      - step::doc.export

  npm.export :
    criterion :
      content : 'npm'
      export : 1
    steps :
      # - build::debug.raw
      # - step::npm.export
      - step::npm.publish

  export :

    criterion :
      default : 1
      export : 1
    steps :
      # - build::npm
      - build::proto.export
      # - build::doc.export
